spring:
  application:
    name: selfkeep

  datasource:
    url: "jdbc:postgresql://localhost:5432/self-keep"
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false

server:
  port: 9000
jwt:
  secret: ${JWT_SECRET}